server {
    listen 3000;
    root /usr/share/nginx/html;
    index index.html;
    autoindex off;

    location / {
        try_files $uri $uri/ /__spa-fallback.html;
    }

    location /assets/ {
        autoindex off;
        try_files $uri =404;
    }

    location /api {
        proxy_pass http://api:8080;
    }
}
